# -*- coding: utf-8 -*-
"""Génère les banques de questions rédigées d'EduMate (data/quiz/*.json)."""
import json
import os

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "quiz")
os.makedirs(OUT, exist_ok=True)

BANKS = {}


def bank(topic, questions):
    BANKS.setdefault(topic, []).extend(questions)


def q(prompt, options, answer, explanation, skill, difficulty="moyen"):
    return {
        "prompt": prompt,
        "options": options,
        "answer": answer,
        "explanation": explanation,
        "skill": skill,
        "difficulty": difficulty,
    }


# ============================ FRANÇAIS ============================
bank("francais-troisieme-methode-redaction", [
    q("Quelle est la structure minimale d’un paragraphe argumentatif au collège ?",
      ["Idée principale, argument, exemple, conclusion partielle",
       "Une seule phrase d’accroche",
       "Trois exemples sans lien entre eux",
       "Une citation sans commentaire"], 0,
      "Un paragraphe développé suit la progression : idée → argument → exemple → mini-conclusion. C’est la règle AEI (affirmer, expliquer, illustrer).",
      "Structure du paragraphe", "facile"),
    q("Que doit contenir l’introduction d’un texte argumentatif ?",
      ["Une accroche, la présentation du sujet, la problématique et l’annonce du plan",
       "Uniquement la thèse défendue",
       "Une conclusion anticipée",
       "Une liste d’exemples"], 0,
      "L’introduction va du général au particulier : accroche, sujet, problématique, annonce du plan.",
      "Introduction", "facile"),
    q("Quel connecteur exprime une conséquence ?",
      ["Par conséquent", "Cependant", "Par exemple", "En effet"], 0,
      "« Par conséquent » introduit la conséquence ; « cependant » l’opposition, « par exemple » l’illustration, « en effet » l’explication.",
      "Connecteurs logiques", "facile"),
    q("Comment introduire correctement une citation dans une rédaction ?",
      ["Entre guillemets, en précisant la source et en l’expliquant",
       "En recopiant le texte sans guillemets",
       "En la plaçant uniquement en conclusion",
       "En la remplaçant par un résumé personnel"], 0,
      "Une citation se signale par des guillemets, s’accompagne de sa source et doit toujours être expliquée pour servir l’argumentation.",
      "Citation", "moyen"),
    q("Quel temps utilise-t-on pour les actions de premier plan d’un récit au passé ?",
      ["Le passé simple", "L’imparfait", "Le présent", "Le futur simple"], 0,
      "Le passé simple exprime les actions ponctuelles et de premier plan ; l’imparfait décrit le décor et les actions duratives.",
      "Temps du récit", "moyen"),
    q("Que faut-il vérifier en priorité lors de la relecture d’une rédaction ?",
      ["L’orthographe, les accords et la cohérence des paragraphes",
       "La longueur du texte uniquement",
       "La beauté de l’écriture manuscrite",
       "Le nombre de citations"], 0,
      "La relecture porte d’abord sur la langue (orthographe, accords, conjugaison) puis sur la cohérence et les transitions.",
      "Relecture", "facile"),
    q("Quel est le rôle d’une phrase de transition entre deux paragraphes ?",
      ["Récapituler l’idée précédente et annoncer la suivante",
       "Répéter la même idée",
       "Introduire une nouvelle citation",
       "Conclure le devoir"], 0,
      "La transition assure la continuité du raisonnement : elle ferme une étape et ouvre la suivante.",
      "Transitions", "moyen"),
    q("Comment éviter les répétitions dans un texte ?",
      ["En utilisant des synonymes et des reprises pronominales",
       "En supprimant tous les adjectifs",
       "En écrivant des phrases très longues",
       "En répétant le mot-clé pour insister"], 0,
      "La variété lexicale (synonymes, périphrases) et les pronoms anaphoriques évitent la répétition tout en maintenant la cohérence.",
      "Cohésion du texte", "moyen"),
])

bank("francais-troisieme-methode-brevet", [
    q("Combien de temps dure l’épreuve écrite de français du brevet ?",
      ["3 heures", "1 heure", "2 heures", "4 heures"], 0,
      "L’épreuve de français du DNB dure 3 heures : grammaire et compétences linguistiques, compréhension de texte, puis rédaction (ou dictée).",
      "Organisation de l’épreuve", "facile"),
    q("Sur combien de points est évaluée la rédaction au brevet ?",
      ["40 points", "10 points", "20 points", "100 points"], 0,
      "La rédaction (sujet d’imagination ou de réflexion) est notée sur 40 points ; l’épreuve écrite compte 100 points.",
      "Barème", "facile"),
    q("Quelle stratégie est la plus efficace pour répondre à une question de compréhension ?",
      ["Citer précisément le texte puis interpréter",
       "Recopier tout le paragraphe",
       "Répondre d’après ses connaissances personnelles",
       "Laisser la réponse vide en cas d’hésitation"], 0,
      "Une réponse complète s’appuie sur une citation exacte (guillemets) puis une interprétation justifiée.",
      "Compréhension de texte", "moyen"),
    q("Que signifie « réécrire » dans l’exercice de réécriture du brevet ?",
      ["Transformer un passage selon une consigne grammaticale précise (temps, personne, nombre)",
       "Recopier le texte à l’identique",
       "Résumer le passage en trois lignes",
       "Traduire le passage"], 0,
      "L’exercice de réécriture porte sur la langue : changement de temps, de personne, de nombre… Il faut être exhaustif et vigilant sur les accords.",
      "Réécriture", "moyen"),
    q("Pour un sujet d’imagination, que faut-il absolument respecter ?",
      ["La consigne, le lien avec le texte ou l’œuvre et la longueur demandée",
       "Uniquement la longueur",
       "L’absence de dialogue",
       "Le récit à la troisième personne"], 0,
      "Un sujet d’imagination reste contraint : respecter la consigne, s’inscrire dans l’univers proposé et tenir la longueur demandée.",
      "Sujet d’imagination", "moyen"),
    q("Dans un sujet de réflexion, comment organiser ses arguments ?",
      ["Un paragraphe par argument, chacun illustré par un exemple précis",
       "Tous les arguments dans un seul paragraphe",
       "Des exemples sans arguments",
       "Une thèse sans justification"], 0,
      "Le sujet de réflexion exige une argumentation structurée : thèse, arguments hiérarchisés, exemples variés (lectures, histoire, actualité).",
      "Sujet de réflexion", "difficile"),
    q("Quelle part du brevet représente la maîtrise du socle commun ?",
      ["400 points sur 800", "100 points sur 800", "50 points sur 800", "200 points sur 800"], 0,
      "Le DNB totalise 800 points : 400 pour le socle commun (évaluation continue) et 400 pour les épreuves écrites et l’oral.",
      "Notation du brevet", "facile"),
    q("Quelle est la meilleure gestion du temps sur les 3 heures de français ?",
      ["Répartir selon le barème et garder 15 minutes de relecture",
       "Passer 2 heures sur la première question",
       "Commencer par la rédaction sans lire le texte",
       "Écrire la dictée en premier"], 0,
      "On proportionne le temps au nombre de points, et on garde systématiquement un temps de relecture finale.",
      "Gestion du temps", "moyen"),
])

bank("francais-seconde-methode-commentaire", [
    q("Quelle est la démarche fondamentale d’un commentaire littéraire ?",
      ["Décrire, expliquer puis interpréter en citant le texte",
       "Raconter l’histoire du passage",
       "Donner son avis personnel sans citation",
       "Résumer le texte paragraphe par paragraphe"], 0,
      "Le commentaire n’est ni un résumé ni une paraphrase : il observe des procédés, les explique et en propose une interprétation justifiée.",
      "Démarche du commentaire", "moyen"),
    q("Qu’est-ce que la paraphrase, écueil majeur du commentaire ?",
      ["Redire le texte avec d’autres mots sans l’analyser",
       "Citer trop précisément le texte",
       "Analyser les figures de style",
       "Proposer un plan en deux parties"], 0,
      "La paraphrase répète le contenu sans en dégager le fonctionnement ni l’intérêt : elle doit être remplacée par l’analyse de procédés.",
      "Paraphrase", "moyen"),
    q("Comment construire les axes d’un commentaire ?",
      ["À partir des effets produits par le texte, et non du déroulement du récit",
       "En suivant l’ordre des paragraphes",
       "En classant les figures de style par ordre alphabétique",
       "En reprenant la biographie de l’auteur"], 0,
      "Un axe répond à la question : « que fait ce texte au lecteur et comment ? » Chaque axe regroupe plusieurs procédés convergents.",
      "Axes d’analyse", "difficile"),
    q("Quelle citation est correctement intégrée dans une phrase d’analyse ?",
      ["Le poète évoque une nature mourante : « les feuilles tombent ».",
       "Les feuilles tombent.",
       "« les feuilles tombent » nature mourante",
       "Le texte dit que les feuilles tombent et c’est triste."], 0,
      "Une citation doit être introduite, encadrée de guillemets et immédiatement suivie d’une analyse (procédé + effet).",
      "Citation et analyse", "moyen"),
    q("Quels procédés repérer en priorité dans un texte poétique ?",
      ["Le rythme, les sonorités, les images et la ponctuation",
       "Uniquement le nombre de strophes",
       "La biographie du poète",
       "Le genre du poème"], 0,
      "En poésie, la forme fait sens : mètres, enjambements, allitérations, assonances, images et ponctuation sont des objets d’analyse.",
      "Analyse poétique", "difficile"),
    q("Que doit contenir la conclusion d’un commentaire ?",
      ["Le bilan des axes et une ouverture pertinente",
       "Une nouvelle analyse du texte",
       "La biographie complète de l’auteur",
       "Le résumé du passage"], 0,
      "La conclusion synthétise la lecture proposée puis ouvre vers une autre œuvre, un autre mouvement ou un enjeu littéraire.",
      "Conclusion", "facile"),
    q("Comment analyser un champ lexical dans un commentaire ?",
      ["Relever les termes, montrer leur cohérence et l’effet produit",
       "Lister les mots sans commentaire",
       "Compter le nombre d’occurrences",
       "Chercher les synonymes dans un dictionnaire"], 0,
      "Le relevé n’a de valeur que s’il débouche sur une interprétation : quel univers le champ lexical construit-il, et pourquoi ?",
      "Champ lexical", "moyen"),
    q("Quel est le rôle de l’introduction d’un commentaire ?",
      ["Situer le texte, dégager une problématique et annoncer le plan",
       "Résumer l’intrigue en détail",
       "Citer le texte intégralement",
       "Présenter la conclusion"], 0,
      "Introduction type : présentation (auteur, œuvre, contexte du passage), caractérisation du texte, problématique, annonce du plan.",
      "Introduction", "moyen"),
])

bank("francais-seconde-methode-dissertation", [
    q("Qu’est-ce qu’une problématique de dissertation ?",
      ["Une question qui met en tension deux réponses également défendables",
       "Le rappel du sujet",
       "Une liste de mots-clés",
       "La conclusion anticipée du devoir"], 0,
      "La problématique naît d’un paradoxe ou d’une ambiguïté du sujet : elle rend le débat nécessaire plutôt que de poser une question fermée.",
      "Problématique", "difficile"),
    q("Quel plan est le plus courant pour une dissertation littéraire ?",
      ["Plan dialectique : thèse, antithèse, dépassement",
       "Plan chronologique imposé",
       "Plan en une seule partie",
       "Plan par œuvres successives"], 0,
      "Le plan dialectique confronte deux positions puis les dépasse ; le plan thématique ou analytique est possible selon le sujet.",
      "Types de plan", "moyen"),
    q("Que doit contenir chaque sous-partie d’une dissertation ?",
      ["Un argument, un exemple précis et une analyse",
       "Uniquement des exemples",
       "Uniquement des citations",
       "Une opinion personnelle non justifiée"], 0,
      "Règle d’or : un paragraphe = une idée, une preuve (œuvre, texte, référence), une explication qui relie l’exemple à l’argument.",
      "Paragraphe argumentatif", "moyen"),
    q("Pourquoi éviter le catalogue d’exemples dans une dissertation ?",
      ["Parce qu’un exemple non analysé ne prouve rien",
       "Parce que les exemples sont interdits",
       "Parce qu’il faut citer uniquement des œuvres du programme",
       "Parce que cela allonge inutilement la conclusion"], 0,
      "La qualité d’une dissertation tient au raisonnement : trois exemples analysés valent mieux que dix exemples énumérés.",
      "Argumentation", "difficile"),
    q("Quelle formulation annonce correctement un plan dans une introduction ?",
      ["« Nous verrons d’abord que…, puis nous montrerons que…, enfin nous nous demanderons si… »",
       "« Je vais parler de… »",
       "« Le plan est le suivant : 1, 2, 3 »",
       "« Voici mes idées »"], 0,
      "L’annonce de plan doit être fluide, rédigée et logique : elle reprend exactement les intitulés des parties.",
      "Annonce du plan", "facile"),
    q("Comment rédiger une transition entre deux parties ?",
      ["En concluant la partie précédente et en justifiant le passage à la suivante",
       "En répétant l’introduction",
       "En sautant une ligne sans texte",
       "En annonçant la conclusion"], 0,
      "La transition assure la continuité du raisonnement : bilan + question qui appelle la partie suivante.",
      "Transitions", "moyen"),
    q("Quel est l’écueil du « hors-sujet » en dissertation ?",
      ["Répondre à une question que le sujet ne pose pas",
       "Citer trop d’œuvres",
       "Utiliser un plan dialectique",
       "Écrire une conclusion longue"], 0,
      "Le hors-sujet vient d’une lecture rapide des termes du sujet : il faut définir chaque mot-clé avant de bâtir le plan.",
      "Hors-sujet", "moyen"),
    q("Quelle longueur vise-t-on pour une dissertation au lycée ?",
      ["4 à 6 pages manuscrites équilibrées entre les parties",
       "1 page maximum",
       "10 pages",
       "Peu importe la longueur"], 0,
      "L’équilibre compte autant que la longueur : des parties de taille comparable témoignent d’une pensée structurée.",
      "Gestion du devoir", "facile"),
])

bank("francais-premiere-methode-contraction", [
    q("Quelle est la règle essentielle de la contraction de texte ?",
      ["Respecter le nombre de mots imposé et conserver le mouvement du texte",
       "Réécrire le texte avec ses propres idées",
       "Supprimer tous les exemples",
       "Traduire le texte en langage familier"], 0,
      "La contraction suit l’ordre et la logique de l’original, reformule sans paraphraser et respecte le quota de mots (± 10 %).",
      "Règles de la contraction", "moyen"),
    q("Comment compter les mots en contraction de texte ?",
      ["Selon la règle officielle : « c’est-à-dire » = 3 mots, « aujourd’hui » = 1 mot",
       "Selon le nombre de lettres",
       "Selon les espaces uniquement, sans exception",
       "Selon son appréciation personnelle"], 0,
      "Tout ce qui est séparé par un signe de ponctuation ou d’espacement compte pour un mot ; « aujourd’hui » compte pour un, « c’est-à-dire » pour trois.",
      "Comptage des mots", "difficile"),
    q("Que faut-il faire avant de rédiger une contraction ?",
      ["Découper le texte en mouvements et reformuler chacun au brouillon",
       "Recopier le texte en supprimant des phrases",
       "Commencer directement la rédaction",
       "Chercher des citations à placer"], 0,
      "La méthode : lecture active, découpage en mouvements, reformulation de chaque mouvement, puis calibrage du nombre de mots.",
      "Méthode de contraction", "moyen"),
    q("Quelle reformulation est acceptable dans une contraction ?",
      ["Une reformulation fidèle au sens, avec ses propres mots",
       "Une copie exacte de la phrase d’origine",
       "Une interprétation personnelle qui change le sens",
       "Une phrase plus longue que l’originale"], 0,
      "On doit reformuler sans trahir : ni démarquage mot à mot, ni contresens, ni ajout d’idées absentes du texte.",
      "Reformulation", "difficile"),
    q("Quel élément doit obligatoirement figurer sur la copie ?",
      ["Le nombre de mots, indiqué en fin de contraction",
       "Le titre du texte",
       "La biographie de l’auteur",
       "Un plan détaillé"], 0,
      "Le candidat reporte le décompte des mots à la fin de sa contraction ; l’oubli ou l’erreur de comptage est sanctionné.",
      "Présentation de la copie", "facile"),
    q("Comment traiter les exemples dans une contraction ?",
      ["Les condenser ou les généraliser, sans supprimer ceux qui portent l’argumentation",
       "Les supprimer systématiquement",
       "Les recopier intégralement",
       "Les remplacer par des exemples personnels"], 0,
      "Un exemple qui illustre l’argument doit être conservé sous forme condensée ; un exemple purement décoratif peut disparaître.",
      "Traitement des exemples", "difficile"),
])

bank("francais-premiere-methode-oral", [
    q("Comment se déroule l’oral de français du bac (épreuve anticipée) ?",
      ["Préparation de 30 minutes, puis exposé et entretien de 20 minutes",
       "10 minutes de préparation, 5 minutes d’exposé",
       "Exposé de 40 minutes sans préparation",
       "Lecture à voix haute uniquement"], 0,
      "L’oral dure 20 minutes après 30 minutes de préparation : explication linéaire, question de grammaire, puis entretien.",
      "Déroulé de l’épreuve", "moyen"),
    q("Quelles sont les étapes attendues d’une explication linéaire ?",
      ["Introduction, lecture, mouvements du texte, analyse progressive, conclusion",
       "Lecture seule",
       "Résumé puis avis personnel",
       "Analyse globale sans suivre le texte"], 0,
      "L’explication linéaire suit le déroulé du texte : on découpe en mouvements et on analyse les procédés dans l’ordre.",
      "Explication linéaire", "moyen"),
    q("Quel est l’objectif de l’entretien avec l’examinateur ?",
      ["Défendre ses lectures, argumenter et montrer sa culture littéraire",
       "Réciter une fiche par cœur",
       "Résumer l’œuvre en une phrase",
       "Éviter toute prise de position"], 0,
      "L’entretien évalue la capacité à dialoguer : justifier un choix de lecture, relier des œuvres, argumenter avec précision.",
      "Entretien", "difficile"),
    q("Que faut-il préparer pour la seconde partie de l’oral ?",
      ["Une œuvre intégrale choisie parmi celles étudiées, à présenter et défendre",
       "Un poème appris par cœur",
       "Une dissertation rédigée",
       "Une fiche de grammaire"], 0,
      "Le candidat présente l’œuvre de son choix parmi la liste, en explique les enjeux et répond aux questions de l’examinateur.",
      "Présentation d’œuvre", "moyen"),
    q("Quelle question de grammaire est typiquement posée à l’oral ?",
      ["Analyser une négation, une interrogation ou une subordonnée du texte",
       "Conjuguer un verbe au subjonctif",
       "Recopier une règle d’accord",
       "Traduire une phrase en latin"], 0,
      "La partie grammaire porte sur l’analyse syntaxique d’un court passage : négation, interrogation, subordonnées.",
      "Grammaire à l’oral", "moyen"),
    q("Comment gérer les 30 minutes de préparation ?",
      ["Bâtir un plan détaillé avec citations et procédés, sans tout rédiger",
       "Rédiger intégralement l’exposé",
       "Recopier le texte au propre",
       "Apprendre par cœur une introduction"], 0,
      "Le temps est limité : on note les mouvements, les procédés, les citations clés et l’analyse de grammaire en style télégraphique.",
      "Gestion de la préparation", "difficile"),
])

# ======================= HISTOIRE-GÉOGRAPHIE / EMC =======================
bank("histoire-geographie-troisieme-emc-republique", [
    q("Quelle est la devise de la République française ?",
      ["Liberté, Égalité, Fraternité", "Liberté, Justice, Paix", "Égalité, Solidarité, Nation", "Travail, Famille, Patrie"], 0,
      "La devise « Liberté, Égalité, Fraternité » figure dans la Constitution ; « Travail, Famille, Patrie » était celle du régime de Vichy.",
      "Symboles de la République", "facile"),
    q("Que signifie le principe de laïcité ?",
      ["La neutralité de l’État vis-à-vis des religions et la liberté de conscience",
       "L’interdiction de toute religion",
       "La reconnaissance d’une religion officielle",
       "Le contrôle des cultes par l’État"], 0,
      "La laïcité sépare les Églises et l’État (loi de 1905) : l’État est neutre, chacun est libre de croire ou de ne pas croire.",
      "Laïcité", "moyen"),
    q("Quel texte fondateur proclame l’égalité des droits en France ?",
      ["La Déclaration des droits de l’homme et du citoyen de 1789",
       "Le Code civil de 1804", "La Charte de 1814", "Le seul préambule de 1946"], 0,
      "La DDHC de 1789 affirme que « les hommes naissent et demeurent libres et égaux en droits » ; elle est reprise dans le préambule de la Constitution de 1958.",
      "Textes fondateurs", "facile"),
    q("Quel symbole de la République incarne la liberté guidant le peuple ?",
      ["Marianne", "Le coq gaulois", "La Marseillaise", "Le 14 juillet"], 0,
      "Marianne incarne la République ; la Marseillaise est l’hymne national, le 14 juillet la fête nationale, le coq un emblème historique.",
      "Symboles", "facile"),
    q("Que garantit le droit de vote en France depuis 1945 ?",
      ["Le suffrage universel direct, libre et secret, y compris pour les femmes",
       "Le vote réservé aux hommes propriétaires",
       "Le vote obligatoire avec amende",
       "Le vote par corporation"], 0,
      "Le suffrage est universel, égal, libre et secret ; les femmes votent depuis 1945, la majorité est à 18 ans depuis 1974.",
      "Suffrage", "moyen"),
    q("Qu’est-ce qu’un service public ?",
      ["Une activité d’intérêt général assurée par l’État ou une collectivité",
       "Une entreprise privée rentable",
       "Un service réservé aux fonctionnaires",
       "Une association caritative"], 0,
      "Le service public répond à un besoin d’intérêt général (éducation, santé, transports) et repose sur l’égalité d’accès, la continuité et l’adaptabilité.",
      "Services publics", "moyen"),
    q("Quel est le rôle du Défenseur des droits ?",
      ["Veiller au respect des droits et libertés par les administrations",
       "Juger les affaires pénales",
       "Diriger la police nationale",
       "Rédiger les lois"], 0,
      "Le Défenseur des droits, autorité constitutionnelle indépendante, peut être saisi gratuitement par toute personne s’estimant lésée.",
      "Institutions", "difficile"),
    q("Pourquoi la liberté d’expression connaît-elle des limites ?",
      ["Parce qu’elle ne doit pas porter atteinte aux droits d’autrui ni à l’ordre public",
       "Parce qu’elle est interdite aux mineurs",
       "Parce qu’elle est réservée aux journalistes",
       "Parce qu’elle n’existe pas en France"], 0,
      "La liberté d’expression est garantie mais encadrée : interdiction de l’injure, de la diffamation, de l’incitation à la haine.",
      "Libertés fondamentales", "difficile"),
])

bank("histoire-geographie-troisieme-emc-citoyennete", [
    q("À quel âge obtient-on la capacité électorale en France ?",
      ["18 ans", "16 ans", "21 ans", "15 ans"], 0,
      "La majorité civile et électorale est fixée à 18 ans depuis 1974.",
      "Citoyenneté", "facile"),
    q("Qu’est-ce qu’un citoyen ?",
      ["Une personne titulaire de la nationalité et des droits civils et politiques",
       "Toute personne habitant en France",
       "Uniquement une personne majeure qui vote",
       "Un fonctionnaire de l’État"], 0,
      "Le citoyen dispose de droits (vote, éligibilité) et de devoirs (respect des lois, impôts, défense).",
      "Citoyenneté", "facile"),
    q("Quelle est la différence entre une loi et un règlement ?",
      ["La loi est votée par le Parlement, le règlement est pris par le pouvoir exécutif",
       "Le règlement est supérieur à la loi",
       "La loi ne concerne que les fonctionnaires",
       "Il n’y a aucune différence"], 0,
      "Dans la hiérarchie des normes, la Constitution prime, puis les traités, la loi, et enfin les règlements (décrets, arrêtés).",
      "Hiérarchie des normes", "moyen"),
    q("Quel est le rôle du Conseil constitutionnel ?",
      ["Vérifier la conformité des lois à la Constitution",
       "Juger les affaires criminelles",
       "Élire le président",
       "Rédiger les lois"], 0,
      "Le Conseil constitutionnel contrôle la constitutionnalité des lois et veille à la régularité des élections nationales.",
      "Institutions", "moyen"),
    q("Qu’est-ce que la nationalité française par droit du sol ?",
      ["L’acquisition de la nationalité par la naissance et la résidence en France",
       "L’acquisition par la filiation uniquement",
       "Une nationalité accordée à tous les touristes",
       "Une procédure réservée aux adultes"], 0,
      "Le droit du sol permet à un enfant né en France de parents étrangers d’acquérir la nationalité sous conditions ; le droit du sang repose sur la filiation.",
      "Nationalité", "moyen"),
    q("Quel engagement citoyen est ouvert dès 16 ans ?",
      ["Le service civique", "Le vote aux élections présidentielles", "L’éligibilité au Parlement", "La fonction de juge"], 0,
      "Le service civique est accessible de 16 à 25 ans : mission d’intérêt général indemnisée.",
      "Engagement", "facile"),
    q("Qu’est-ce qu’une association loi 1901 ?",
      ["Un groupement de personnes à but non lucratif, librement constitué",
       "Une entreprise commerciale",
       "Un organisme public",
       "Un parti politique obligatoire"], 0,
      "La loi du 1er juillet 1901 garantit la liberté d’association : deux personnes au moins, but non lucratif, déclaration en préfecture.",
      "Engagement associatif", "moyen"),
    q("Quels sont les trois pouvoirs distingués par Montesquieu ?",
      ["Législatif, exécutif, judiciaire", "Fédéral, local, national", "Militaire, civil, religieux", "Économique, social, culturel"], 0,
      "La séparation des pouvoirs (L’Esprit des lois, 1748) est un principe fondamental de l’État de droit.",
      "Séparation des pouvoirs", "moyen"),
])

bank("histoire-geographie-seconde-methode-document", [
    q("Quels éléments faut-il présenter pour identifier un document historique ?",
      ["Nature, auteur, date, contexte, destinataire",
       "Uniquement le titre",
       "Le nombre de pages",
       "L’avis personnel de l’historien"], 0,
      "La présentation critique d’un document suit la grille : nature, auteur, date, contexte, source, destinataire, intention.",
      "Analyse critique", "moyen"),
    q("Pourquoi la date d’un document est-elle essentielle ?",
      ["Parce qu’elle détermine le contexte historique et la portée du propos",
       "Parce qu’elle permet de classer les documents par ordre alphabétique",
       "Parce qu’elle indique la longueur du texte",
       "Parce qu’elle est exigée par le correcteur uniquement"], 0,
      "Un document se comprend dans son contexte : la même phrase n’a pas le même sens selon qu’elle est écrite avant ou après un événement majeur.",
      "Contextualisation", "moyen"),
    q("Comment distinguer un document source d’un document historiographique ?",
      ["Le document source date de l’époque étudiée ; le document historiographique est produit plus tard par un historien",
       "Le document source est toujours plus long",
       "L’historiographie est toujours un tableau",
       "Il n’y a aucune différence"], 0,
      "Un document de première main (témoignage, loi, affiche) s’oppose à un document de seconde main (manuel, article d’historien).",
      "Typologie des documents", "difficile"),
    q("Que signifie « critiquer » un document en histoire ?",
      ["Interroger sa fiabilité, son point de vue et ses intentions",
       "Dire que le document est mauvais",
       "Comparer sa date avec celle d’un autre document",
       "Recopier le document"], 0,
      "La critique externe porte sur l’authenticité, la critique interne sur la cohérence et la sincérité du contenu.",
      "Critique historique", "difficile"),
    q("Comment utiliser un témoignage comme document historique ?",
      ["En le croisant avec d’autres sources pour vérifier sa fiabilité",
       "En le recopiant intégralement",
       "En l’acceptant sans réserve",
       "En l’écartant systématiquement"], 0,
      "Un témoignage est subjectif : il informe sur les représentations de son auteur et doit être confronté à d’autres documents.",
      "Croisement des sources", "difficile"),
    q("Que faire des silences d’un document ?",
      ["Les signaler et expliquer pourquoi certaines informations sont absentes",
       "Les ignorer",
       "Les inventer pour compléter",
       "Les considérer comme des erreurs"], 0,
      "Ce qu’un document ne dit pas est aussi une information : censure, oubli, angle de vue choisi par l’auteur.",
      "Analyse critique", "difficile"),
])

bank("histoire-geographie-seconde-methode-croquis", [
    q("Que doit contenir un croquis de géographie complet ?",
      ["Un titre, une légende organisée et des figurés adaptés",
       "Uniquement des couleurs",
       "Une carte calquée sur Internet",
       "Un paragraphe rédigé"], 0,
      "Les trois éléments notés : titre précis, légende hiérarchisée en parties, figurés (ponctuels, linéaires, de surface) cohérents.",
      "Composition d’un croquis", "moyen"),
    q("Quel type de figuré utilise-t-on pour représenter une ville ?",
      ["Un figuré ponctuel proportionnel à son importance",
       "Un figuré linéaire",
       "Une flèche",
       "Un aplat de couleur"], 0,
      "Les figurés ponctuels localisent des points (villes, ports) ; leur taille exprime une hiérarchie.",
      "Figurés ponctuels", "facile"),
    q("Comment représenter un flux sur un croquis ?",
      ["Par une flèche dont l’épaisseur est proportionnelle à l’intensité du flux",
       "Par un cercle",
       "Par un dégradé de couleurs",
       "Par une hachure"], 0,
      "Les figurés linéaires (flèches) traduisent les échanges, migrations ou transports ; l’épaisseur hiérarchise.",
      "Flux", "moyen"),
    q("Comment organiser la légende d’un croquis ?",
      ["En deux ou trois parties correspondant aux axes du sujet",
       "Par ordre alphabétique",
       "En listant tous les figurés sans regroupement",
       "En ne mettant que les couleurs"], 0,
      "La légende est un mini-plan : elle suit la problématique et regroupe les figurés par idée directrice.",
      "Légende", "difficile"),
    q("Pourquoi hiérarchiser les couleurs dans un croquis ?",
      ["Pour traduire des intensités et rendre la lecture immédiate",
       "Pour remplir l’espace",
       "Parce que trois couleurs sont obligatoires",
       "Pour décorer la carte"], 0,
      "Les dégradés (du clair au foncé) expriment des intensités ; le choix des couleurs doit rester cohérent et lisible.",
      "Sémiologie graphique", "moyen"),
    q("Quelle erreur évite-t-on en soignant le titre d’un croquis ?",
      ["Un titre vague qui ne répond pas au sujet",
       "Un titre trop long",
       "Un titre en majuscules",
       "L’absence de date"], 0,
      "Le titre doit reformuler la problématique du sujet, être précis et placé en haut du croquis.",
      "Titre", "facile"),
])

# ============================ PHYSIQUE-CHIMIE ============================
bank("physique-chimie-premiere-chimie-oxydoreduction", [
    q("Qu’est-ce qu’une oxydation ?",
      ["Une perte d’électrons", "Un gain d’électrons", "Une perte de protons", "Un gain de neutrons"], 0,
      "Oxydation = perte d’électrons ; réduction = gain d’électrons. Moyen mnémotechnique : OIL RIG (Oxidation Is Loss, Reduction Is Gain).",
      "Oxydation", "moyen"),
    q("Qu’est-ce qu’un couple oxydant/réducteur ?",
      ["Deux espèces qui échangent des électrons, notées Ox/Red",
       "Deux ions de même charge",
       "Un acide et sa base conjuguée",
       "Deux isotopes d’un même élément"], 0,
      "Un couple redox réunit l’oxydant et le réducteur conjugués : Ox + n e⁻ = Red (ex. Cu²⁺/Cu).",
      "Couples redox", "moyen"),
    q("Dans une pile, où se produit l’oxydation ?",
      ["À l’anode, pôle négatif", "À la cathode, pôle positif", "Dans le pont salin", "Au niveau du sel fondu"], 0,
      "L’oxydation a toujours lieu à l’anode (pôle − d’une pile) ; la réduction à la cathode (pôle +).",
      "Piles", "difficile"),
    q("Quelle demi-équation correspond à la réduction de l’ion cuivre(II) ?",
      ["Cu²⁺ + 2 e⁻ → Cu", "Cu → Cu²⁺ + 2 e⁻", "Cu²⁺ → Cu + 2 e⁻", "Cu + 2 e⁻ → Cu²⁺"], 0,
      "La réduction est un gain d’électrons : Cu²⁺ capte 2 électrons pour donner le cuivre métallique.",
      "Demi-équations", "moyen"),
    q("Quel est le nombre d’oxydation du soufre dans H₂SO₄ ?",
      ["+VI", "+IV", "−II", "+II"], 0,
      "H est +I, O est −II : 2(+1) + S + 4(−2) = 0, donc S = +6.",
      "Nombre d’oxydation", "difficile"),
    q("Comment équilibrer une équation d’oxydoréduction ?",
      ["En égalisant le nombre d’électrons échangés entre les deux demi-équations",
       "En ajoutant de l’eau au hasard",
       "En modifiant uniquement les coefficients de l’oxygène",
       "En inversant les réactifs"], 0,
      "On écrit les deux demi-équations, on multiplie chacune pour égaliser les électrons, puis on les additionne.",
      "Équilibrage redox", "difficile"),
    q("Quel rôle joue le pont salin dans une pile ?",
      ["Assurer la continuité électrique et la neutralité des solutions",
       "Augmenter la tension",
       "Empêcher la réaction",
       "Conserver les électrodes"], 0,
      "Le pont salin laisse passer les ions : il ferme le circuit et évite l’accumulation de charges.",
      "Piles", "moyen"),
    q("Que se passe-t-il lors de la corrosion du fer ?",
      ["Le fer est oxydé par le dioxygène en présence d’eau",
       "Le fer est réduit", "Le fer se sublime", "Le fer devient un isolant"], 0,
      "Le fer perd des électrons (Fe → Fe²⁺ + 2 e⁻) au contact de O₂ et de l’humidité : formation de la rouille.",
      "Corrosion", "moyen"),
])

bank("physique-chimie-premiere-chimie-organique", [
    q("Quelle est la formule générale d’un alcane ?",
      ["CnH2n+2", "CnH2n", "CnH2n−2", "CnHn"], 0,
      "Les alcanes sont saturés : CnH2n+2 (méthane CH₄, éthane C₂H₆…). Les alcènes suivent CnH2n.",
      "Familles organiques", "moyen"),
    q("Quel groupe caractéristique définit un alcool ?",
      ["Le groupe hydroxyle −OH porté par un carbone saturé",
       "Le groupe carbonyle C=O",
       "Le groupe carboxyle −COOH",
       "Le groupe amine −NH₂"], 0,
      "Alcool : R−OH ; aldéhyde/cétone : C=O ; acide carboxylique : −COOH ; amine : −NH₂.",
      "Groupes caractéristiques", "moyen"),
    q("Comment nomme-t-on le composé CH₃−CH₂−CH₂−OH ?",
      ["Propan-1-ol", "Propanal", "Acide propanoïque", "Propanone"], 0,
      "Chaîne à 3 carbones (propane), groupe −OH sur le carbone 1 : propan-1-ol.",
      "Nomenclature", "moyen"),
    q("Quelle isomérie présente deux composés de même formule brute mais d’enchaînement différent ?",
      ["L’isomérie de constitution", "La stéréoisomérie de conformation", "L’isomérie Z/E", "L’isomérie optique"], 0,
      "Les isomères de constitution diffèrent par l’enchaînement des atomes ; les stéréoisomères ont le même enchaînement mais une disposition spatiale différente.",
      "Isomérie", "difficile"),
    q("Quelle est la formule brute de l’éthanol ?",
      ["C₂H₆O", "C₂H₄O₂", "CH₄O", "C₃H₈O"], 0,
      "L’éthanol CH₃−CH₂−OH compte 2 C, 6 H et 1 O : C₂H₆O.",
      "Formules brutes", "facile"),
    q("Qu’est-ce qu’une distillation fractionnée ?",
      ["Une séparation de liquides miscibles fondée sur leurs températures d’ébullition différentes",
       "Une filtration sur papier",
       "Une extraction par solvant",
       "Une décantation"], 0,
      "La colonne de Vigreux multiplie les cycles vaporisation-condensation : on sépare les constituants selon leur volatilité.",
      "Séparation", "moyen"),
    q("Quel est l’alcane à quatre atomes de carbone ?",
      ["Le butane", "Le propane", "Le pentane", "L’éthane"], 0,
      "Méthane (1 C), éthane (2), propane (3), butane (4), pentane (5), hexane (6).",
      "Nomenclature", "facile"),
    q("Que signifie « saturation » en chimie organique ?",
      ["La molécule ne contient que des liaisons simples carbone-carbone",
       "La molécule contient une double liaison",
       "La solution est concentrée au maximum",
       "La molécule est cyclique"], 0,
      "Un hydrocarbure saturé (alcane) ne possède que des liaisons simples C−C ; un insaturé contient au moins une double ou triple liaison.",
      "Saturation", "moyen"),
])

# ============================ PHILOSOPHIE ============================
bank("philosophie-terminale-methode-dissertation", [
    q("Que faut-il faire en tout premier lieu face à un sujet de dissertation ?",
      ["Analyser chaque terme du sujet et repérer le présupposé ou le paradoxe",
       "Chercher immédiatement un plan",
       "Recopier le cours correspondant",
       "Rédiger l’introduction"], 0,
      "L’analyse des termes (définitions, distinctions, enjeux) fait apparaître la difficulté du sujet et donc la problématique.",
      "Analyse du sujet", "difficile"),
    q("Quelle est la différence entre une question de cours et un problème philosophique ?",
      ["Le problème naît d’une difficulté réelle : deux réponses également défendables s’opposent",
       "Il n’y a aucune différence",
       "La question de cours est plus difficile",
       "Le problème philosophique appelle une réponse scientifique"], 0,
      "Une dissertation ne récite pas : elle construit une réponse à une difficulté contenue dans le sujet.",
      "Problématisation", "difficile"),
    q("Comment formuler une bonne problématique ?",
      ["Sous forme d’alternative : le sujet invite-t-il à affirmer X, alors que Y semble vrai aussi ?",
       "Par une question fermée appelant oui ou non",
       "En reprenant le libellé du sujet",
       "Par une citation d’auteur"], 0,
      "La problématique explicite la tension : elle met en balance deux thèses également fondées.",
      "Problématisation", "difficile"),
    q("Quel est le rôle d’une référence philosophique dans une dissertation ?",
      ["Appuyer un argument précis, pas décorer le devoir",
       "Remplacer l’argumentation",
       "Montrer l’étendue de ses connaissances",
       "Ouvrir chaque paragraphe"], 0,
      "Une référence est convoquée pour trancher une difficulté : on l’expose, on la discute, on montre ce qu’elle apporte au raisonnement.",
      "Usage des références", "difficile"),
    q("Que doit faire la troisième partie d’un plan dialectique réussi ?",
      ["Dépasser l’opposition en déplaçant ou en redéfinissant la question",
       "Répéter la thèse initiale",
       "Ajouter des exemples supplémentaires",
       "Conclure le devoir"], 0,
      "Le dépassement n’est pas un compromis mou : il révèle une distinction conceptuelle qui résout la tension initiale.",
      "Dépassement", "difficile"),
    q("Quelle erreur consiste à juxtaposer des opinions sans les justifier ?",
      ["Le doxographique : exposer des avis sans les discuter",
       "La digression", "Le hors-sujet", "La paraphrase"], 0,
      "La philosophie exige des raisons : chaque position doit être argumentée, puis évaluée.",
      "Argumentation", "moyen"),
    q("Comment conclure une dissertation philosophique ?",
      ["Bilan du parcours, réponse nette à la problématique, ouverture éventuelle",
       "En résumant chaque partie mot à mot",
       "En posant une nouvelle question sans bilan",
       "En citant un auteur célèbre"], 0,
      "La conclusion ferme le problème : elle rappelle la réponse obtenue et peut ouvrir sur un enjeu voisin, sans le substituer au bilan.",
      "Conclusion", "moyen"),
    q("Quel est l’intérêt d’un exemple concret dans une dissertation ?",
      ["Éprouver la validité d’une thèse sur un cas précis",
       "Remplir la copie", "Illustrer sans analyser", "Remplacer un argument"], 0,
      "Un bon exemple est analysé : il montre ce que la thèse explique ou ce qu’elle échoue à expliquer.",
      "Usage de l’exemple", "moyen"),
])

bank("philosophie-terminale-methode-explication", [
    q("Quelle est la première étape d’une explication de texte philosophique ?",
      ["Identifier le thème, la thèse et le problème du texte",
       "Chercher des références extérieures",
       "Résumer le texte paragraphe par paragraphe",
       "Rédiger la conclusion"], 0,
      "Avant d’expliquer, on dégage : de quoi parle le texte (thème), ce qu’il affirme (thèse), à quelle question il répond (problème).",
      "Lecture méthodique", "moyen"),
    q("Qu’est-ce qu’expliquer un texte, par opposition à le paraphraser ?",
      ["Élucider les articulations, les concepts et les enjeux du raisonnement",
       "Redire le texte avec d’autres mots",
       "Donner son avis sur le texte",
       "Réduire le texte à une citation"], 0,
      "Expliquer, c’est montrer comment le texte avance : définitions, oppositions, exemples, réfutations, conclusions.",
      "Explication", "difficile"),
    q("Peut-on discuter la thèse de l’auteur dans une explication de texte ?",
      ["Oui, dans l’intérêt du texte et à partir d’objections précises",
       "Non, jamais", "Oui, mais seulement en conclusion", "Non, sauf si l’auteur est connu"], 0,
      "La discussion n’est pas une opinion : elle confronte la thèse à une objection argumentée ou à une autre position philosophique.",
      "Discussion", "difficile"),
    q("Comment dégager les mouvements d’un texte ?",
      ["En suivant les connecteurs logiques et les changements de fonction du discours",
       "En comptant les paragraphes",
       "En repérant les citations",
       "En suivant l’ordre alphabétique des notions"], 0,
      "Les mouvements correspondent aux étapes du raisonnement : poser, argumenter, réfuter, illustrer, conclure.",
      "Structure du texte", "moyen"),
    q("Que faut-il faire des notions techniques rencontrées dans un texte ?",
      ["Les définir précisément et montrer leur rôle dans l’argumentation",
       "Les remplacer par des synonymes courants",
       "Les ignorer",
       "Les citer sans les expliquer"], 0,
      "Un concept philosophique (nature, culture, liberté…) porte la thèse : son sens dans le texte doit être explicité.",
      "Analyse conceptuelle", "difficile"),
    q("Quelle organisation attend-on d’une explication de texte au bac ?",
      ["Introduction, explication ordonnée suivant les mouvements, conclusion",
       "Une seule partie",
       "Un résumé suivi d’un avis",
       "Une liste de citations"], 0,
      "L’épreuve dure 4 heures ; l’explication suit le texte dans son ordre en dégageant sa logique propre.",
      "Organisation de l’épreuve", "facile"),
])

bank("philosophie-terminale-methode-problematique", [
    q("Comment reconnaître qu’un sujet contient un problème philosophique ?",
      ["Il oppose deux réponses également justifiables ou contient un présupposé discutable",
       "Il est formulé sous forme de question",
       "Il contient un mot difficile",
       "Il fait référence à un auteur"], 0,
      "Le problème naît d’une alternative réelle : sans tension, il n’y a qu’une question de définition ou de fait.",
      "Problématisation", "difficile"),
    q("Que signifie « discuter un présupposé » ?",
      ["Interroger ce que le sujet tient pour acquis sans le justifier",
       "Contredire systématiquement le sujet",
       "Ajouter une hypothèse personnelle",
       "Changer les termes du sujet"], 0,
      "Exemple : « la technique nous rend-elle plus libres ? » présuppose que la liberté peut se mesurer ; discuter, c’est examiner ce présupposé.",
      "Présupposés", "difficile"),
    q("Quelle distinction conceptuelle est souvent utile ?",
      ["Celle qui sépare deux sens d’un même mot dans le sujet",
       "Celle qui oppose deux auteurs",
       "Celle qui sépare le passé du présent",
       "Celle qui oppose science et opinion"], 0,
      "Beaucoup de sujets se débloquent en distinguant deux acceptions d’un terme (ex. « libre » au sens juridique et au sens métaphysique).",
      "Distinctions conceptuelles", "difficile"),
    q("Quel est l’objectif de l’alternative initiale ?",
      ["Exposer les deux thèses que le sujet rend également plausibles",
       "Donner immédiatement la réponse",
       "Citer deux auteurs opposés",
       "Annoncer le plan en trois temps"], 0,
      "L’alternative met en évidence la difficulté : « On peut soutenir X…, mais Y semble tout aussi fondé… »",
      "Alternative", "moyen"),
    q("Quel écueil consiste à transformer le sujet en récitation de cours ?",
      ["Le placage de cours", "Le hors-sujet", "La paraphrase", "La digression"], 0,
      "Le cours doit être mobilisé pour répondre à la question posée, jamais récité comme une fin en soi.",
      "Écueils", "moyen"),
    q("Comment vérifier qu’une problématique est bien construite ?",
      ["Elle contient une tension, elle est née du sujet, et un plan peut y répondre",
       "Elle est courte", "Elle cite un auteur", "Elle commence par « pourquoi »"], 0,
      "Test pratique : si deux personnes raisonnables peuvent répondre différemment, la problématique est authentiquement philosophique.",
      "Contrôle de la problématique", "difficile"),
])

# ============================ ANGLAIS ============================
bank("anglais-premiere-methode-ecrit", [
    q("How should you organise a formal English essay?",
      ["Introduction with a thesis, body paragraphs with one idea each, conclusion",
       "One single long paragraph",
       "Bullet points only",
       "Conclusion first, then arguments"], 0,
      "A formal essay follows: introduction (hook + thesis), body paragraphs (topic sentence, evidence, analysis), conclusion (restatement + opening).",
      "Essay structure", "moyen"),
    q("Which linking word expresses a concession?",
      ["However", "Therefore", "Moreover", "For instance"], 0,
      "\"However\" introduces a contrast or concession; \"therefore\" a consequence, \"moreover\" an addition, \"for instance\" an example.",
      "Linking words", "facile"),
    q("How do you introduce a personal opinion in an argumentative text?",
      ["\"In my view…\" / \"From my point of view…\"",
       "\"I think maybe perhaps…\"",
       "\"Everybody knows that…\"",
       "\"It is obvious for all people…\""], 0,
      "Academic phrasing: \"In my view\", \"I would argue that\", \"It seems to me that\". Avoid over-generalisations.",
      "Expressing opinion", "moyen"),
    q("What is the difference between \"although\" and \"however\"?",
      ["\"Although\" is a subordinating conjunction, \"however\" is an adverb linking two sentences",
       "They are interchangeable",
       "\"However\" is only used orally",
       "\"Although\" expresses consequence"], 0,
      "\"Although + clause\" cannot stand alone; \"however\" starts a new sentence and is followed by a comma.",
      "Grammar in writing", "difficile"),
    q("Which is the best way to paraphrase a source text?",
      ["Restate the idea with different words and structure, keeping the meaning",
       "Copy the sentence and change one word",
       "Translate word for word",
       "Quote without quotation marks"], 0,
      "Paraphrasing requires changing both vocabulary and syntax while preserving the original meaning; quoting requires quotation marks.",
      "Paraphrase", "moyen"),
    q("How should a synthesis of two documents be written?",
      ["By comparing and contrasting their ideas, not by summarising them one after the other",
       "By summarising document A, then document B",
       "By translating both documents",
       "By quoting the longest passages"], 0,
      "A synthesis is organised around themes or points of agreement/disagreement between the documents.",
      "Synthesis", "difficile"),
    q("Which tense is generally used to comment on a novel or film?",
      ["The present simple (\"literary present\")",
       "The past simple",
       "The present perfect continuous",
       "The future"], 0,
      "In English, analysis of a text or film uses the present tense: \"Hamlet hesitates\", \"the narrator questions…\".",
      "Literary present", "moyen"),
    q("What is a topic sentence?",
      ["The first sentence of a paragraph announcing its main idea",
       "The last sentence of the essay",
       "The title of the text",
       "A sentence with no verb"], 0,
      "Each body paragraph opens with a topic sentence stating the idea developed in the rest of the paragraph.",
      "Paragraph structure", "facile"),
])

bank("anglais-terminale-methode-oral", [
    q("How should you begin an oral presentation in English?",
      ["Greet the examiners, state the topic and announce your plan",
       "Read your notes silently",
       "Start with a long quotation",
       "Apologise for your level"], 0,
      "A strong opening: greeting, presentation of the document/issue, announcement of the plan. It builds confidence and clarity.",
      "Oral presentation", "moyen"),
    q("What is the best way to handle a question you did not understand?",
      ["Ask politely for clarification: \"Could you rephrase that, please?\"",
       "Stay silent",
       "Change the subject",
       "Answer in French"], 0,
      "Interaction is assessed: reformulating the question or asking for clarification shows communicative competence.",
      "Interaction", "moyen"),
    q("Which strategy improves fluency during the oral exam?",
      ["Using fillers naturally and keeping speaking without long pauses",
       "Speaking as fast as possible",
       "Memorising a full script word for word",
       "Avoiding all linking words"], 0,
      "Fluency comes from connected speech: \"well\", \"actually\", \"as a matter of fact\" give thinking time while keeping the flow.",
      "Fluency", "difficile"),
    q("How should you present a document (article, cartoon, speech)?",
      ["Nature, author, source, date, topic, then the main argument",
       "Only the title",
       "Only your personal opinion",
       "Only the vocabulary list"], 0,
      "The presentation grid: type of document, author, source, date, subject, thesis, structure, tone.",
      "Document analysis", "moyen"),
    q("What is expected in the personal reaction part of the oral?",
      ["A justified personal standpoint linked to cultural knowledge",
       "A simple \"I like it\"",
       "A summary of the document",
       "A list of vocabulary"], 0,
      "Examiners assess the ability to argue: opinion + reason + example (from the notion studied, current affairs, or personal experience).",
      "Argumentation", "difficile"),
    q("How can you show cultural knowledge during the oral?",
      ["By referring to key notions, historical references and studied documents",
       "By quoting French celebrities",
       "By speaking only about your hobbies",
       "By avoiding all references"], 0,
      "The programme notions (identity, citizenship, progress, etc.) provide the framework: connect the document to them explicitly.",
      "Cultural knowledge", "difficile"),
])

# ============================ SES ============================
bank("ses-terminale-methode-dissertation", [
    q("Quelle est la première étape d’une dissertation en SES ?",
      ["Analyser le sujet et définir précisément les notions clés",
       "Rédiger l’introduction",
       "Chercher des chiffres",
       "Construire le plan définitif"], 0,
      "La définition rigoureuse des notions (croissance, chômage, justice sociale…) conditionne tout le devoir.",
      "Analyse du sujet", "moyen"),
    q("Quel type de preuve est le plus attendu en SES ?",
      ["Des données chiffrées sourcées et des références théoriques",
       "Des opinions personnelles",
       "Des exemples fictifs",
       "Des citations littéraires"], 0,
      "Une dissertation de SES articule théorie (auteurs, mécanismes) et faits (statistiques INSEE, OCDE, exemples historiques datés).",
      "Argumentation chiffrée", "difficile"),
    q("Comment mobiliser un mécanisme économique dans un devoir ?",
      ["En explicitant la chaîne causale : cause → mécanisme → conséquence",
       "En citant seulement le nom du mécanisme",
       "En donnant un chiffre sans explication",
       "En recopiant la définition du cours"], 0,
      "Exemple : baisse des taux → crédit moins cher → investissement et consommation → demande → croissance.",
      "Raisonnement économique", "difficile"),
    q("Quelle est la fonction d’une référence à un auteur en SES ?",
      ["Appuyer un argument en précisant son apport et ses limites",
       "Remplir une page",
       "Remplacer une donnée chiffrée",
       "Décorer l’introduction"], 0,
      "Une référence efficace : nom de l’auteur, thèse, mécanisme proposé, et éventuellement critique (validité, contexte).",
      "Références théoriques", "difficile"),
    q("Quel plan convient au sujet « La croissance est-elle compatible avec l’environnement ? »",
      ["Un plan dialectique : compatibilité, contradictions, dépassement par la soutenabilité",
       "Un plan chronologique",
       "Un plan par pays",
       "Un plan en une seule partie"], 0,
      "Le sujet oppose deux termes : on examine la compatibilité, puis les contradictions, puis on dépasse par la soutenabilité forte/faible et les instruments de politique économique.",
      "Construction du plan", "difficile"),
    q("Que doit contenir l’introduction d’une dissertation de SES ?",
      ["Accroche, définition des termes, problématique, annonce du plan",
       "Uniquement la problématique",
       "Un graphique",
       "La conclusion"], 0,
      "Introduction en quatre temps : accroche (fait d’actualité ou donnée), analyse des notions, problématique, annonce du plan.",
      "Introduction", "moyen"),
    q("Comment conclure une dissertation en SES ?",
      ["Bilan de la démonstration, réponse nette et ouverture sur un enjeu proche",
       "En résumant chaque partie mot à mot",
       "En posant une nouvelle question sans bilan",
       "En citant un auteur sans commentaire"], 0,
      "La conclusion tranche le problème posé et peut ouvrir sur un débat voisin (ex. indicateurs alternatifs au PIB).",
      "Conclusion", "moyen"),
    q("Quelle erreur pénalise le plus une copie de SES ?",
      ["Le catalogue de connaissances sans lien avec le sujet",
       "Un plan en trois parties",
       "Des chiffres arrondis",
       "Une introduction de dix lignes"], 0,
      "Le correcteur attend une démonstration : chaque élément du cours doit servir l’argumentation du sujet.",
      "Écueils", "moyen"),
])

# ============================ ÉCRITURE DES FICHIERS ============================
SUBJECT_PREFIXES = [
    "histoire-geographie",
    "physique-chimie",
    "mathematiques",
    "philosophie",
    "francais",
    "anglais",
    "espagnol",
    "ses",
    "nsi",
    "svt",
]


def subject_of(topic):
    for prefix in SUBJECT_PREFIXES:
        if topic.startswith(prefix):
            return prefix
    return topic.split("-")[0]


groups = {}
for topic, questions in BANKS.items():
    groups.setdefault(subject_of(topic), []).append({"topic": topic, "questions": questions})

total_q = 0
for subject, banks in sorted(groups.items()):
    path = os.path.join(OUT, f"{subject}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"banks": banks}, f, ensure_ascii=False, indent=1)
    n = sum(len(b["questions"]) for b in banks)
    total_q += n
    print(f"{os.path.basename(path)}: {len(banks)} banques, {n} questions")
print(f"TOTAL : {total_q} questions rédigées")
